[build-system]
requires = [ "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "MLp"
dynamic = [ "dependencies", "version"]

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"

[tool.setuptools.dynamic.version]
attr = "MLp.__version__"
